slam_toolbox:
  ros__parameters:

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odom

    mode: mapping

    use_sim_time: false

    map_update_interval: 1.0
    resolution: 0.05

    minimum_time_interval: 0.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    transform_timeout: 1.0
    tf_buffer_duration: 60.0

    throttle_scans: 1

    max_laser_range: 8.0
    min_laser_range: 0.1
